# Site settings
title: Alexander Meise
tag_text: Alexander Meise
description: Alexander Meise's personal page with CV and additional information. Get to know me!

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
