# Site settings
title: alexmeise
tag_text: Personal Site
description: This is intended to present my cv and contact information.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
